/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.0
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class key_command_lcmt implements lcm.lcm.LCMEncodable
{
    public short use_tau_mapping_rl;

    public short use_ankle_motor_kd_rl;

    public long timestamp_us;

    public long id;

    public long robot_id;

 
    public key_command_lcmt()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x3d45a7605aa27fc0L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.key_command_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.key_command_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeShort(this.use_tau_mapping_rl); 
 
        outs.writeShort(this.use_ankle_motor_kd_rl); 
 
        outs.writeLong(this.timestamp_us); 
 
        outs.writeLong(this.id); 
 
        outs.writeLong(this.robot_id); 
 
    }
 
    public key_command_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public key_command_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.key_command_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.key_command_lcmt o = new lcmtypes.key_command_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.use_tau_mapping_rl = ins.readShort();
 
        this.use_ankle_motor_kd_rl = ins.readShort();
 
        this.timestamp_us = ins.readLong();
 
        this.id = ins.readLong();
 
        this.robot_id = ins.readLong();
 
    }
 
    public lcmtypes.key_command_lcmt copy()
    {
        lcmtypes.key_command_lcmt outobj = new lcmtypes.key_command_lcmt();
        outobj.use_tau_mapping_rl = this.use_tau_mapping_rl;
 
        outobj.use_ankle_motor_kd_rl = this.use_ankle_motor_kd_rl;
 
        outobj.timestamp_us = this.timestamp_us;
 
        outobj.id = this.id;
 
        outobj.robot_id = this.robot_id;
 
        return outobj;
    }
 
}

