/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.0
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class tau_mapping_lcmt implements lcm.lcm.LCMEncodable
{
    /**
     * LCM Type: float[4]
     */
    public float tau_est[];

    public long timestamp_us;

    public long id;

    public long robot_id;

 
    public tau_mapping_lcmt()
    {
        tau_est = new float[4];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xf8222c17e895ec24L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.tau_mapping_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.tau_mapping_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.tau_est[a]); 
        }
 
        outs.writeLong(this.timestamp_us); 
 
        outs.writeLong(this.id); 
 
        outs.writeLong(this.robot_id); 
 
    }
 
    public tau_mapping_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public tau_mapping_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.tau_mapping_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.tau_mapping_lcmt o = new lcmtypes.tau_mapping_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.tau_est = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.tau_est[a] = ins.readFloat();
        }
 
        this.timestamp_us = ins.readLong();
 
        this.id = ins.readLong();
 
        this.robot_id = ins.readLong();
 
    }
 
    public lcmtypes.tau_mapping_lcmt copy()
    {
        lcmtypes.tau_mapping_lcmt outobj = new lcmtypes.tau_mapping_lcmt();
        outobj.tau_est = new float[(int) 4];
        System.arraycopy(this.tau_est, 0, outobj.tau_est, 0, 4); 
        outobj.timestamp_us = this.timestamp_us;
 
        outobj.id = this.id;
 
        outobj.robot_id = this.robot_id;
 
        return outobj;
    }
 
}

